
@adminUser = Authorization: Basic smeUser smePwd

### Read all services
GET http://localhost:4004/odata/v4/CatalogService


### Read all services
GET http://localhost:4004/odata/v4/CatalogService/$metadata
{{adminUser}}

### Read 
GET http://localhost:4004/odata/v4/CatalogService/EmployeeService

### Create
POST http://localhost:4004/odata/v4/CatalogService/EmployeeService
Content-Type: application/json

{
      "Currency_code": "USD",
      "ID": "02BD2137-0890-1EEA-A6C2-BB55C197CCCC",
      "accountNumber": "111222000",
      "bankId": "510000115",
      "bankName": "My Bank of Mumbai",
      "email": "Mr.RAM@itelo.info",
      "gender": "F",
      "language": "E",
      "loginName": "MRSHYAM",
      "nameFirst": "Mr",
      "nameInitials": null,
      "nameLast": "SHYAM",
      "nameMiddle": null,
      "phoneNumber": "+1 124 374 524",
      "salaryAmount": "145549.00"
}

### Update
PATCH  http://localhost:4004/odata/v4/CatalogService/EmployeeService/02BD2137-0890-1EEA-A6C2-BB55C197AAAA
Content-Type: application/json

{
    "salaryAmount" : "100001.00",
    "Currency_code" : "EUR"
}

### Delete
DELETE  http://localhost:4004/odata/v4/CatalogService/EmployeeService/02BD2137-0890-1EEA-A6C2-BB55C197AAAA

### Read top 5 employees
GET http://localhost:4004/odata/v4/CatalogService/EmployeeService?$top=5&$skip=5

### Single Employee
GET http://localhost:4004/odata/v4/CatalogService/EmployeeService/02BD2137-0890-1EEA-A6C2-BB55C197E7FB

###
GET http://localhost:4004/odata/v4/CatalogService/PurchaseOrderService?$expand=Items


### Create
POST http://localhost:4004/odata/v4/CatalogService/createEmployee
Content-Type: application/json

{
      "Currency_code": "USD",
      "ID": "02BD2137-0890-1EEA-A6C2-BB55C197DDDD",
      "accountNumber": "111222111",
      "bankId": "510000111",
      "bankName": "My Bank of Delhi",
      "email": "Mr.KALYAN@itelo.info",
      "gender": "F",
      "language": "E",
      "loginName": "MRKALYAN",
      "nameFirst": "Mr",
      "nameInitials": null,
      "nameLast": "KALYAN",
      "nameMiddle": null,
      "phoneNumber": "+1 124 374 524",
      "salaryAmount": "15549.00"
}

###
GET http://localhost:4004/odata/v4/CatalogService/getMaleEmployees()

POST http://localhost:4004/odata/v4/CatalogService/PurchaseOrderService
Content-Type: : application/json

{

}

###
POST http://localhost:4004/odata/v4/CatalogService/PurchaseOrderService/74867AD200E41EDBA5D8B0C98DC28052/discountOnPrice
Content-Type: application/json

{
      
}

###
GET http://localhost:4004/odata/v4/CatalogService/PurchaseOrderService/74867AD200E41EDBA5D8B0C98DC28052/smallestOrder()

###
GET http://localhost:4004/odata/v4/CatalogService/PurchaseOrderService/74867AD200E41EDBA5D8B0C98DC28052/largestOrder() retunrs 


###
POST http://localhost:4004/odata/v4/CatalogService/PO
Content-Type: application/json

{
      "poId" : "300030303",
      "poName": "ABCD",
      "linkToContact": "RawMaterial"
}


###
POST http://localhost:4004/odata/v4/CatalogService/ItemPO
Content-Type: application/json

{
      "poItem" : "RawMaterial",
      "poName": "Raw",
      "poPhone": "989890"
}